package View;

/**
 *
 * @author 1 Irawansyah
 * 
 */

public class viewProfileUser1 extends javax.swing.JFrame {

    /**
     * Creates new form vProfileUser1 
     */
    public viewProfileUser1() {
        initComponents();
        this.setLocation(515, 45);
        setSize(360,640);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b3BarProfileUser1 = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutProfileUser1 = new javax.swing.JButton();
        bAccount = new javax.swing.JButton();
        labelAccount = new javax.swing.JLabel();
        bNotif = new javax.swing.JButton();
        labelNotif = new javax.swing.JLabel();
        bSetting = new javax.swing.JButton();
        labelSetting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        b3BarProfileUser1.setBackground(new java.awt.Color(255, 255, 255));
        b3BarProfileUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarProfileUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarProfileUser1ActionPerformed(evt);
            }
        });

        labelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("Account");

        bLogoutProfileUser1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutProfileUser1.setText("Logout");
        bLogoutProfileUser1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLogoutProfileUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutProfileUser1ActionPerformed(evt);
            }
        });

        bAccount.setBackground(new java.awt.Color(255, 255, 255));
        bAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Account (1).png"))); // NOI18N
        bAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccountActionPerformed(evt);
            }
        });

        labelAccount.setBackground(new java.awt.Color(255, 255, 255));
        labelAccount.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelAccount.setText("Profile");

        bNotif.setBackground(new java.awt.Color(255, 255, 255));
        bNotif.setForeground(new java.awt.Color(255, 255, 255));
        bNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Notif (1).png"))); // NOI18N
        bNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotifActionPerformed(evt);
            }
        });

        labelNotif.setBackground(new java.awt.Color(255, 255, 255));
        labelNotif.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelNotif.setText("Notification");

        bSetting.setBackground(new java.awt.Color(255, 255, 255));
        bSetting.setForeground(new java.awt.Color(255, 255, 255));
        bSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Setting.png"))); // NOI18N
        bSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSettingActionPerformed(evt);
            }
        });

        labelSetting.setBackground(new java.awt.Color(255, 255, 255));
        labelSetting.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelSetting.setText("Setting");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b3BarProfileUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(bLogoutProfileUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarProfileUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogoutProfileUser1)
                            .addComponent(labelDashboard))))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelAccount)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelNotif)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelSetting)))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAccountActionPerformed

    private void b3BarProfileUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarProfileUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarProfileUser1ActionPerformed

    private void bNotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNotifActionPerformed

    private void bLogoutProfileUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutProfileUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutProfileUser1ActionPerformed

    private void bSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSettingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarProfileUser1;
    private javax.swing.JButton bAccount;
    private javax.swing.JButton bLogoutProfileUser1;
    private javax.swing.JButton bNotif;
    private javax.swing.JButton bSetting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelNotif;
    private javax.swing.JLabel labelSetting;
    // End of variables declaration//GEN-END:variables

}
