package View;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */

public class viewLoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vLoginAdmin
     */
    public viewLoginAdmin() {
        initComponents();
        this.setLocation(515, 45);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWelcome = new javax.swing.JLabel();
        labelNgampusYuk = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        tfIDAdmin = new javax.swing.JTextField();
        pfPasswordAdmin = new javax.swing.JPasswordField();
        cboxRememberAdmin = new javax.swing.JCheckBox();
        btnLoginAdmin = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        labelWelcome.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelWelcome.setText("Welcome to");
        getContentPane().add(labelWelcome);
        labelWelcome.setBounds(115, 30, 117, 30);

        labelNgampusYuk.setBackground(new java.awt.Color(255, 255, 255));
        labelNgampusYuk.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelNgampusYuk.setText("NgampusYuk!");
        getContentPane().add(labelNgampusYuk);
        labelNgampusYuk.setBounds(107, 60, 133, 30);

        labelLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelLogin.setText("Login Admin");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(111, 120, 123, 30);

        tfIDAdmin.setText("ID Admin");
        tfIDAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDAdminActionPerformed(evt);
            }
        });
        getContentPane().add(tfIDAdmin);
        tfIDAdmin.setBounds(50, 200, 260, 40);

        pfPasswordAdmin.setText("jPasswordField1");
        pfPasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordAdminActionPerformed(evt);
            }
        });
        getContentPane().add(pfPasswordAdmin);
        pfPasswordAdmin.setBounds(50, 255, 260, 40);

        cboxRememberAdmin.setText("Remember Me");
        cboxRememberAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRememberAdminActionPerformed(evt);
            }
        });
        getContentPane().add(cboxRememberAdmin);
        cboxRememberAdmin.setBounds(50, 305, 130, 23);

        btnLoginAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Next.png"))); // NOI18N
        btnLoginAdmin.setBorder(null);
        btnLoginAdmin.setBorderPainted(false);
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginAdmin);
        btnLoginAdmin.setBounds(290, 445, 31, 31);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Grouping.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    private void tfIDAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDAdminActionPerformed

    private void pfPasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordAdminActionPerformed

    private void cboxRememberAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRememberAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRememberAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JCheckBox cboxRememberAdmin;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNgampusYuk;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPasswordField pfPasswordAdmin;
    private javax.swing.JTextField tfIDAdmin;
    // End of variables declaration//GEN-END:variables
}
