package View;

import javax.swing.JCheckBox;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 1 Irsyad Muhamad Al Anshori
 * 
 */

public class viewSignUp extends javax.swing.JFrame {

    /**
     * Creates new form vSignUp
     */
    public viewSignUp() {
        initComponents();
        setSize(360,640);
        this.setLocation(515, 45);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfFullName = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        cboxAgree = new javax.swing.JCheckBox();
        bSignUp = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        labelAlreadyHaveAcc = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfFullName.setForeground(new java.awt.Color(102, 102, 102));
        tfFullName.setText("Full Name");
        tfFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFullNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfFullName);
        tfFullName.setBounds(52, 245, 260, 30);

        tfGender.setForeground(new java.awt.Color(102, 102, 102));
        tfGender.setText("Gender");
        tfGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenderActionPerformed(evt);
            }
        });
        getContentPane().add(tfGender);
        tfGender.setBounds(52, 285, 260, 30);

        tfEmail.setForeground(new java.awt.Color(102, 102, 102));
        tfEmail.setText("Email or Phone Number");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(52, 325, 260, 30);

        tfPassword.setForeground(new java.awt.Color(102, 102, 102));
        tfPassword.setText("jPasswordField1");
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(52, 365, 260, 30);

        cboxAgree.setForeground(new java.awt.Color(255, 255, 255));
        cboxAgree.setText("Agree to Our Terms & Condition");
        cboxAgree.setContentAreaFilled(false);
        cboxAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxAgreeActionPerformed(evt);
            }
        });
        getContentPane().add(cboxAgree);
        cboxAgree.setBounds(52, 400, 230, 23);

        bSignUp.setBackground(new java.awt.Color(255, 255, 255));
        bSignUp.setForeground(new java.awt.Color(255, 255, 255));
        bSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button SignUp.png"))); // NOI18N
        bSignUp.setBorder(null);
        bSignUp.setBorderPainted(false);
        bSignUp.setContentAreaFilled(false);
        bSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(bSignUp);
        bSignUp.setBounds(130, 440, 90, 40);

        bLogin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Login.png"))); // NOI18N
        bLogin.setBorder(null);
        bLogin.setContentAreaFilled(false);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(130, 510, 90, 30);

        labelAlreadyHaveAcc.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlreadyHaveAcc.setForeground(new java.awt.Color(255, 255, 255));
        labelAlreadyHaveAcc.setText("Already have an account?");
        getContentPane().add(labelAlreadyHaveAcc);
        labelAlreadyHaveAcc.setBounds(115, 490, 130, 15);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-SignUp.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void bSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignUpActionPerformed

    private void tfFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFullNameActionPerformed

    private void tfGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenderActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void cboxAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxAgreeActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox cboxAgree;
    private javax.swing.JLabel labelAlreadyHaveAcc;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfGender;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables

    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }    

    // BUTTON
    
    public JButton getBLogin() {
        return bLogin;
    }

    public JButton getBSignUp() {
        return bSignUp;
    }

    public JCheckBox getCboxAgree() {
        return cboxAgree;
    }

    // TEXT FIELD
    
    public void set(String x) {
        tfEmail.setText(x);
        tfFullName.setText(x);
        tfGender.setText(x);
        tfPassword.setText(x);
        
    }
    
    public String getTfEmail() {
        return tfEmail.getText();
    }
    
    public String getTfFullName() {
        return tfFullName.getText();
    }
    
    public String getTfGender() {
        return tfGender.getText();
    }
    
    public String getTfPassword() {
        return tfPassword.getText();
    }

//    public void setTfEmail(String x) {
//        tfEmail.setText(x);
//    }
//
//    public void setTfFullName(String x) {
//        tfFullName.setText(x);
//    }
//
//    public void setTfGender(String x) {
//        tfGender.setText(x);
//    }
//
//    public void setTfPassword(String x) {
//        tfPassword.setText(x);
//    }
    
    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        bLogin.addActionListener(e);
        bSignUp.addActionListener(e);
    }
    
    // RESET
    
    public void reset(){
        set("");
//        setTfEmail("");
//        setTfFullName("");
//        setTfGender("");
//        setTfPassword("");
    }
}
