package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 1 Ifdhal Hadi
 * @author 2 Irsyad Muhamad Al Anshori
 * 
 */

public class viewMenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public viewMenuUser() {
        initComponents();
        //setSize(360,640);
        this.setLocation(515, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama = new javax.swing.JPanel();
        b3BarMUser = new javax.swing.JButton();
        bLogoutMUser = new javax.swing.JButton();
        bTestMBTI = new javax.swing.JButton();
        bCollegeInfo = new javax.swing.JButton();
        bListPersonality = new javax.swing.JButton();
        bAnnounce = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Profile = new javax.swing.JButton();
        Email = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nama.setBackground(new java.awt.Color(255, 255, 255));
        Nama.setPreferredSize(new java.awt.Dimension(360, 640));
        Nama.setLayout(null);

        b3BarMUser.setBackground(new java.awt.Color(255, 255, 255));
        b3BarMUser.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarMUser.setBorder(null);
        b3BarMUser.setBorderPainted(false);
        b3BarMUser.setContentAreaFilled(false);
        b3BarMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarMUserActionPerformed(evt);
            }
        });
        Nama.add(b3BarMUser);
        b3BarMUser.setBounds(21, 45, 15, 27);

        bLogoutMUser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutMUser.setBorder(null);
        bLogoutMUser.setBorderPainted(false);
        bLogoutMUser.setContentAreaFilled(false);
        bLogoutMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMUserActionPerformed(evt);
            }
        });
        Nama.add(bLogoutMUser);
        bLogoutMUser.setBounds(260, 105, 90, 30);

        bTestMBTI.setBackground(new java.awt.Color(255, 255, 255));
        bTestMBTI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MBTI Test.png"))); // NOI18N
        bTestMBTI.setBorder(null);
        bTestMBTI.setBorderPainted(false);
        bTestMBTI.setContentAreaFilled(false);
        bTestMBTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTestMBTIActionPerformed(evt);
            }
        });
        Nama.add(bTestMBTI);
        bTestMBTI.setBounds(55, 188, 100, 100);

        bCollegeInfo.setBackground(new java.awt.Color(255, 255, 255));
        bCollegeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/College Information.png"))); // NOI18N
        bCollegeInfo.setBorder(null);
        bCollegeInfo.setBorderPainted(false);
        bCollegeInfo.setContentAreaFilled(false);
        bCollegeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCollegeInfoActionPerformed(evt);
            }
        });
        Nama.add(bCollegeInfo);
        bCollegeInfo.setBounds(204, 190, 100, 110);

        bListPersonality.setBackground(new java.awt.Color(255, 255, 255));
        bListPersonality.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/List Personality.png"))); // NOI18N
        bListPersonality.setBorder(null);
        bListPersonality.setBorderPainted(false);
        bListPersonality.setContentAreaFilled(false);
        bListPersonality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListPersonalityActionPerformed(evt);
            }
        });
        Nama.add(bListPersonality);
        bListPersonality.setBounds(45, 335, 120, 100);

        bAnnounce.setBackground(new java.awt.Color(255, 255, 255));
        bAnnounce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Announcement.png"))); // NOI18N
        bAnnounce.setBorder(null);
        bAnnounce.setBorderPainted(false);
        bAnnounce.setContentAreaFilled(false);
        bAnnounce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnounceActionPerformed(evt);
            }
        });
        Nama.add(bAnnounce);
        bAnnounce.setBounds(195, 335, 115, 100);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Halo,");
        Nama.add(jLabel1);
        jLabel1.setBounds(71, 116, 30, 14);

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Acc.png"))); // NOI18N
        Profile.setContentAreaFilled(false);
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        Nama.add(Profile);
        Profile.setBounds(10, 101, 51, 48);

        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("jLabel2");
        Nama.add(Email);
        Email.setBounds(103, 116, 130, 14);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-MenuUtama.png"))); // NOI18N
        background.setText("jLabel2");
        Nama.add(background);
        background.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTestMBTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTestMBTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTestMBTIActionPerformed

    private void bLogoutMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutMUserActionPerformed

    private void bCollegeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCollegeInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCollegeInfoActionPerformed

    private void bListPersonalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListPersonalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bListPersonalityActionPerformed

    private void bAnnounceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnounceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAnnounceActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void b3BarMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarMUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarMUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Nama;
    private javax.swing.JButton Profile;
    private javax.swing.JButton b3BarMUser;
    private javax.swing.JButton bAnnounce;
    private javax.swing.JButton bCollegeInfo;
    private javax.swing.JButton bListPersonality;
    private javax.swing.JButton bLogoutMUser;
    private javax.swing.JButton bTestMBTI;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    // BUTTON
    
    public JButton getB3BarMUser() {
        return b3BarMUser;
    }

    public JButton getBAnnounce() {
        return bAnnounce;
    }

    public JButton getBCollegeInfo() {
        return bCollegeInfo;
    }

    public JButton getBLogoutMUser() {
        return bLogoutMUser;
    }

    public JButton getBMBTIResult() {
        return bListPersonality;
    }

    public JButton getBTestMBTI() {
        return bTestMBTI;
    }

    public JButton getProfile() {
        return Profile;
    }

    public void setEmail(String Email) {
        this.Email.setText(Email);
    }
    
    

    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        b3BarMUser.addActionListener(e);
        bAnnounce.addActionListener(e);
        bCollegeInfo.addActionListener(e);
        bLogoutMUser.addActionListener(e);
        bListPersonality.addActionListener(e);
        bTestMBTI.addActionListener(e);
        Profile.addActionListener(e);
    }
}
