package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */

public class viewLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form vLogin
     */
    public viewLogin() {
        initComponents();
        setSize(375,675);
        this.setLocation(515, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfEmail = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        cboxRemember = new javax.swing.JCheckBox();
        bLogin = new javax.swing.JButton();
        labelDontHaveAcc = new javax.swing.JLabel();
        bSignUp = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfEmail.setForeground(new java.awt.Color(102, 102, 102));
        tfEmail.setText("Email or Phone Number");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(55, 255, 260, 30);

        pfPassword.setForeground(new java.awt.Color(102, 102, 102));
        pfPassword.setText("jPasswordField1");
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfPassword);
        pfPassword.setBounds(55, 295, 260, 30);

        cboxRemember.setForeground(new java.awt.Color(255, 255, 255));
        cboxRemember.setText("Remember Me");
        cboxRemember.setBorder(null);
        cboxRemember.setContentAreaFilled(false);
        cboxRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRememberActionPerformed(evt);
            }
        });
        getContentPane().add(cboxRemember);
        cboxRemember.setBounds(55, 335, 130, 15);

        bLogin.setBackground(new java.awt.Color(255, 255, 255));
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Login.png"))); // NOI18N
        bLogin.setBorder(null);
        bLogin.setBorderPainted(false);
        bLogin.setContentAreaFilled(false);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(130, 385, 90, 30);

        labelDontHaveAcc.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDontHaveAcc.setForeground(new java.awt.Color(255, 255, 255));
        labelDontHaveAcc.setText("Don't have an account?");
        getContentPane().add(labelDontHaveAcc);
        labelDontHaveAcc.setBounds(118, 430, 120, 15);

        bSignUp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button SignUp.png"))); // NOI18N
        bSignUp.setBorder(null);
        bSignUp.setBorderPainted(false);
        bSignUp.setContentAreaFilled(false);
        bSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(bSignUp);
        bSignUp.setBounds(130, 450, 90, 30);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-Login.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void bSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignUpActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void cboxRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRememberActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox cboxRemember;
    private javax.swing.JLabel labelDontHaveAcc;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables

    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    // BUTTON
    
    public JButton getBLogin() {
        return bLogin;
    }
       
    public JButton getBSignUp() {
        return bSignUp;
    }
    
    public JCheckBox getCboxRemember() {
        return cboxRemember;
    }

    // TEXT FIELD
    
    public String getTfEmail() {
        return tfEmail.getText();
    }
    
    public String getPfPassword() {
        return pfPassword.getText();
    }

    public void set(String x) {
        this.tfEmail.setText(x);
        this.pfPassword.setText(x);
    }
    
//    public void setTfEmail(String x) {
//        this.tfEmail.setText(x);
//    }
//        
//    public void setPfPassword(String x) {
//        this.pfPassword.setText(x);
//    }
    
    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        bLogin.addActionListener(e);
        bSignUp.addActionListener(e);
    }
    
    // RESET
    
    public void reset(){
        set("");
//        setTfEmail("");
//        setPfPassword("");
    }
    
}
