package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 1 Irsyad Muhamad Al Anshori
 * 
 */

public class viewCampProfileUnpad extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileUnpad
     */
    public viewCampProfileUnpad() {
        initComponents();
        setSize(375,675);
        this.setLocation(515, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3BarUnpad = new javax.swing.JButton();
        bLogoutUnpad = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3BarUnpad.setBackground(new java.awt.Color(255, 255, 255));
        b3BarUnpad.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarUnpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarUnpad.setBorder(null);
        b3BarUnpad.setContentAreaFilled(false);
        getContentPane().add(b3BarUnpad);
        b3BarUnpad.setBounds(21, 45, 15, 30);

        bLogoutUnpad.setBackground(new java.awt.Color(255, 255, 255));
        bLogoutUnpad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutUnpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutUnpad.setBorder(null);
        bLogoutUnpad.setBorderPainted(false);
        bLogoutUnpad.setContentAreaFilled(false);
        getContentPane().add(bLogoutUnpad);
        bLogoutUnpad.setBounds(260, 105, 90, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Profile Unpad.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarUnpad;
    private javax.swing.JButton bLogoutUnpad;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    // BUTTON
    
    public JButton getB3BarUnpad() {
        return b3BarUnpad;
    }

    public JButton getbLogoutUnpad() {
        return bLogoutUnpad;
    }

    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
       bLogoutUnpad.addActionListener(e);
       b3BarUnpad.addActionListener(e);
   }
}
