package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 1 Irawansyah
 * 
 */

public class viewJudgingVsPerceiving extends javax.swing.JFrame {

    /**
     * Creates new form vDeskripISTP
     */
    public viewJudgingVsPerceiving() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JudgingVsPerceiving = new javax.swing.ButtonGroup();
        btn3bar = new javax.swing.JButton();
        Judging = new javax.swing.JRadioButton();
        Perceiving = new javax.swing.JRadioButton();
        btnLogout = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn3bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        btn3bar.setBorder(null);
        btn3bar.setBorderPainted(false);
        btn3bar.setContentAreaFilled(false);
        getContentPane().add(btn3bar);
        btn3bar.setBounds(21, 45, 15, 27);

        Judging.setBackground(new java.awt.Color(255, 255, 255));
        JudgingVsPerceiving.add(Judging);
        Judging.setContentAreaFilled(false);
        getContentPane().add(Judging);
        Judging.setBounds(35, 237, 21, 21);

        Perceiving.setBackground(new java.awt.Color(255, 255, 255));
        JudgingVsPerceiving.add(Perceiving);
        Perceiving.setContentAreaFilled(false);
        getContentPane().add(Perceiving);
        Perceiving.setBounds(35, 285, 21, 21);

        btnLogout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout);
        btnLogout.setBounds(260, 105, 87, 27);

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Next.png"))); // NOI18N
        Next.setBorder(null);
        Next.setBorderPainted(false);
        Next.setContentAreaFilled(false);
        getContentPane().add(Next);
        Next.setBounds(137, 394, 87, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tes MBTI Soal 4.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Judging;
    private javax.swing.ButtonGroup JudgingVsPerceiving;
    private javax.swing.JButton Next;
    private javax.swing.JRadioButton Perceiving;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn3bar;
    private javax.swing.JButton btnLogout;
    // End of variables declaration//GEN-END:variables

    public String getJudging() {
        if(Judging.isSelected()){
            return "J";     //return Judging
        }else if(Perceiving.isSelected()){
            return "P";     //return Perceiving
        }
        return "null";
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtn3bar() {
        return btn3bar;
    }

    public JButton getNext() {
        return Next;
    }

//    public JButton getBack() {
//        return Back;
//    }
    
    public void addActionListener (ActionListener e) {
        Perceiving.addActionListener(e);
        Judging.addActionListener(e);
        btnLogout.addActionListener(e);
        btn3bar.addActionListener(e);
        Next.addActionListener(e);
//        Back.addActionListener(e);
    }

}
