package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 1 Ifdhal Hadi
 * @author 2 Irsyad Muhamad Al Anhsori
 * 
 */

public class viewCampProfileITB extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileITB
     */
    public viewCampProfileITB() {
        initComponents();
        setSize(375,675);
        this.setLocation(515, 45);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3BarITB = new javax.swing.JButton();
        bLogoutITB = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3BarITB.setBackground(new java.awt.Color(255, 255, 255));
        b3BarITB.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarITB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarITB.setBorder(null);
        b3BarITB.setBorderPainted(false);
        b3BarITB.setContentAreaFilled(false);
        getContentPane().add(b3BarITB);
        b3BarITB.setBounds(21, 45, 15, 30);

        bLogoutITB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutITB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutITB.setBorder(null);
        bLogoutITB.setBorderPainted(false);
        bLogoutITB.setContentAreaFilled(false);
        bLogoutITB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutITBActionPerformed(evt);
            }
        });
        getContentPane().add(bLogoutITB);
        bLogoutITB.setBounds(260, 105, 90, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Profile ITB.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutITBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutITBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutITBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarITB;
    private javax.swing.JButton bLogoutITB;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    // BUTTON
    
    public JButton getB3BarITB() {
        return b3BarITB;
    }

    public JButton getBLogoutITB() {
        return bLogoutITB;
    }

    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
       bLogoutITB.addActionListener(e);
       b3BarITB.addActionListener(e);
   }
    
}
