package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 1 Kamila Hanum
 * @author 2 Irsyad Muhamad Al Anshori
 * @author 3 Irawansyah
 * 
 */

public class viewInputScore extends javax.swing.JFrame {

    /**
     * Creates new form InputScore
     */
    public viewInputScore() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3BarInputScore = new javax.swing.JButton();
        bLogoutInputScore = new javax.swing.JButton();
        bIPA = new javax.swing.JButton();
        bIPS = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3BarInputScore.setBackground(new java.awt.Color(255, 255, 255));
        b3BarInputScore.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarInputScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarInputScore.setBorder(null);
        b3BarInputScore.setBorderPainted(false);
        b3BarInputScore.setContentAreaFilled(false);
        getContentPane().add(b3BarInputScore);
        b3BarInputScore.setBounds(21, 45, 15, 27);

        bLogoutInputScore.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutInputScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutInputScore.setBorder(null);
        bLogoutInputScore.setBorderPainted(false);
        bLogoutInputScore.setContentAreaFilled(false);
        getContentPane().add(bLogoutInputScore);
        bLogoutInputScore.setBounds(260, 105, 87, 27);

        bIPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button IPA.png"))); // NOI18N
        bIPA.setBorder(null);
        bIPA.setBorderPainted(false);
        bIPA.setContentAreaFilled(false);
        getContentPane().add(bIPA);
        bIPA.setBounds(55, 230, 250, 40);

        bIPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button IPS.png"))); // NOI18N
        bIPS.setBorder(null);
        bIPS.setBorderPainted(false);
        bIPS.setContentAreaFilled(false);
        getContentPane().add(bIPS);
        bIPS.setBounds(55, 295, 250, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-Pilih Jurusan.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarInputScore;
    private javax.swing.JButton bIPA;
    private javax.swing.JButton bIPS;
    private javax.swing.JButton bLogoutInputScore;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    // BUTTON
    
    public JButton getbIPA() {
        return bIPA;
    }

    public JButton getbIPS() {
        return bIPS;
    }

    public JButton getB3BarInputScore() {
        return b3BarInputScore;
    }

    public JButton getbLogoutInputScore() {
        return bLogoutInputScore;
    }
    

    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        b3BarInputScore.addActionListener(e);
        bLogoutInputScore.addActionListener(e);
        bIPA.addActionListener(e);
        bIPS.addActionListener(e);
    }
}
