package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author Ifdhal Hadi
 * 
 */

public class viewThinkingVsFeeling extends javax.swing.JFrame {

    /**
     * Creates new form vDeskripISTP
     */
    public viewThinkingVsFeeling() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThingkingVsFeeling = new javax.swing.ButtonGroup();
        btn3bar = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        Thinking = new javax.swing.JRadioButton();
        Feeling = new javax.swing.JRadioButton();
        Next = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn3bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        btn3bar.setBorder(null);
        btn3bar.setBorderPainted(false);
        btn3bar.setContentAreaFilled(false);
        getContentPane().add(btn3bar);
        btn3bar.setBounds(21, 45, 15, 27);

        btnLogout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout);
        btnLogout.setBounds(260, 105, 87, 27);

        Thinking.setBackground(new java.awt.Color(255, 255, 255));
        ThingkingVsFeeling.add(Thinking);
        Thinking.setContentAreaFilled(false);
        getContentPane().add(Thinking);
        Thinking.setBounds(35, 237, 21, 21);

        Feeling.setBackground(new java.awt.Color(255, 255, 255));
        ThingkingVsFeeling.add(Feeling);
        Feeling.setContentAreaFilled(false);
        getContentPane().add(Feeling);
        Feeling.setBounds(35, 285, 21, 21);

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Next.png"))); // NOI18N
        Next.setBorder(null);
        Next.setBorderPainted(false);
        Next.setContentAreaFilled(false);
        getContentPane().add(Next);
        Next.setBounds(137, 394, 87, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tes MBTI Soal 3.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Feeling;
    private javax.swing.JButton Next;
    private javax.swing.ButtonGroup ThingkingVsFeeling;
    private javax.swing.JRadioButton Thinking;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn3bar;
    private javax.swing.JButton btnLogout;
    // End of variables declaration//GEN-END:variables

    public String getFeeling() {
        if(Thinking.isSelected()){
            return "T";     //return Thinking
        } else if(Feeling.isSelected()){
            return "F";     //return Intution
        }
        return "null";
    }

//    public JRadioButton getThinking() {
//        return Thinking;
//    }

    public JButton getBtn3bar() {
        return btn3bar;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getNext() {
        return Next;
    }

//    public JButton getBack() {
//        return Back;
//    }
    
    public void addActionListener (ActionListener e) {
        Feeling.addActionListener(e);
        Thinking.addActionListener(e);
        btn3bar.addActionListener(e);
        btnLogout.addActionListener(e);
        Next.addActionListener(e);
//        Back.addActionListener(e);
    }
}
