package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 1 Ifdhal Hadi
 * @author 2 Irsyad Muhamad Al Anshori
 * 
 */

public class viewCampProfileUPI extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileUPI
     */
    public viewCampProfileUPI() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3BarUPI = new javax.swing.JButton();
        bLogoutUPI = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3BarUPI.setBackground(new java.awt.Color(255, 255, 255));
        b3BarUPI.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarUPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarUPI.setBorder(null);
        b3BarUPI.setBorderPainted(false);
        b3BarUPI.setContentAreaFilled(false);
        getContentPane().add(b3BarUPI);
        b3BarUPI.setBounds(21, 45, 15, 27);

        bLogoutUPI.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutUPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutUPI.setBorder(null);
        bLogoutUPI.setBorderPainted(false);
        bLogoutUPI.setContentAreaFilled(false);
        getContentPane().add(bLogoutUPI);
        bLogoutUPI.setBounds(260, 105, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Profile UPI.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarUPI;
    private javax.swing.JButton bLogoutUPI;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    // BUTTON
    
    public JButton getB3BarUPI() {
        return b3BarUPI;
    }

    public JButton getbLogoutUPI() {
        return bLogoutUPI;
    }
    
    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
       bLogoutUPI.addActionListener(e);
       b3BarUPI.addActionListener(e);
   }
}
