package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 1 Kamila Hanum
 * 
 */

public class viewCampProfileTelU extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileTelU
     */
    public viewCampProfileTelU() {
        initComponents();
        setSize(375,675);
        this.setLocation(515, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3BarTelU = new javax.swing.JButton();
        bLogoutTelU = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3BarTelU.setBackground(new java.awt.Color(255, 255, 255));
        b3BarTelU.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarTelU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarTelU.setBorder(null);
        b3BarTelU.setBorderPainted(false);
        b3BarTelU.setContentAreaFilled(false);
        getContentPane().add(b3BarTelU);
        b3BarTelU.setBounds(21, 45, 15, 27);

        bLogoutTelU.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutTelU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutTelU.setBorder(null);
        bLogoutTelU.setBorderPainted(false);
        bLogoutTelU.setContentAreaFilled(false);
        getContentPane().add(bLogoutTelU);
        bLogoutTelU.setBounds(260, 105, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Profile Telyu.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarTelU;
    private javax.swing.JButton bLogoutTelU;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    // BUTTON
    
    public JButton getB3BarTelU() {
        return b3BarTelU;
    }

    public JButton getBLogoutTelU() {
        return bLogoutTelU;
    }
    
    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
       bLogoutTelU.addActionListener(e);
       b3BarTelU.addActionListener(e);
   }
    
}
