package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author 1 Ifdhal Hadi
 * @author 2 Irsyad Muhamad Al Anhsori
 * 
 */

public class viewAnnouncement extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileITB
     */
    public viewAnnouncement() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3Bar = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Telkom1 = new javax.swing.JLabel();
        Telkom2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3Bar.setBackground(new java.awt.Color(255, 255, 255));
        b3Bar.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3Bar.setBorder(null);
        b3Bar.setBorderPainted(false);
        b3Bar.setContentAreaFilled(false);
        getContentPane().add(b3Bar);
        b3Bar.setBounds(21, 45, 15, 27);

        bLogout.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogout.setBorder(null);
        bLogout.setBorderPainted(false);
        bLogout.setContentAreaFilled(false);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(bLogout);
        bLogout.setBounds(260, 105, 90, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Annoucement.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 150, 320, 121);

        Telkom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/HasilTest/banner-international-class-telkom-university_gelombang2.jpg"))); // NOI18N
        getContentPane().add(Telkom1);
        Telkom1.setBounds(23, 285, 320, 121);

        Telkom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/HasilTest/webbanner-kelas-lanjutan-01-min-min.jpg"))); // NOI18N
        getContentPane().add(Telkom2);
        Telkom2.setBounds(28, 420, 309, 115);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-Announcement.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Telkom1;
    private javax.swing.JLabel Telkom2;
    private javax.swing.JButton b3Bar;
    private javax.swing.JButton bLogout;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    // BUTTON
    
    public JButton getB3Bar() {
        return b3Bar;
    }

    public JButton getBLogout() {
        return bLogout;
    }

    public JLabel getjLabel1() {
        return Telkom1;
    }

    
    public JLabel getjLabel4() {
        return Telkom2;
    }
    
    public JLabel getjLabel3() {
        return jLabel3;
    }
    
    public void addMouseAdapter(MouseAdapter x){
        Telkom1.addMouseListener(x);
        jLabel3.addMouseListener(x);
        Telkom2.addMouseListener(x);
    }



    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
       bLogout.addActionListener(e);
       b3Bar.addActionListener(e);
   }
}
