package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 1 Irsyad Muhamad Al Anshori
 * @author 2 Irawansyah
 * 
 */

public class viewInputScoreIPA extends javax.swing.JFrame {

    /**
     * Creates new form InputScore
     */
    public viewInputScoreIPA() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3Bar = new javax.swing.JButton();
        bLogoutInputScore = new javax.swing.JButton();
        TFIndonesia = new javax.swing.JTextField();
        TFInggris = new javax.swing.JTextField();
        TFMtk = new javax.swing.JTextField();
        TFPilihan = new javax.swing.JTextField();
        bLanjut = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b3Bar.setBackground(new java.awt.Color(255, 255, 255));
        b3Bar.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3Bar.setBorder(null);
        b3Bar.setBorderPainted(false);
        b3Bar.setContentAreaFilled(false);
        getContentPane().add(b3Bar);
        b3Bar.setBounds(21, 45, 15, 27);

        bLogoutInputScore.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutInputScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutInputScore.setBorder(null);
        bLogoutInputScore.setBorderPainted(false);
        bLogoutInputScore.setContentAreaFilled(false);
        getContentPane().add(bLogoutInputScore);
        bLogoutInputScore.setBounds(260, 105, 87, 27);

        TFIndonesia.setForeground(new java.awt.Color(102, 102, 102));
        TFIndonesia.setText("Nilai Rata-Rata Semster 1 - 5");
        getContentPane().add(TFIndonesia);
        TFIndonesia.setBounds(55, 252, 250, 25);

        TFInggris.setForeground(new java.awt.Color(102, 102, 102));
        TFInggris.setText("Nilai Rata-Rata Semster 1 - 5");
        TFInggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFInggrisActionPerformed(evt);
            }
        });
        getContentPane().add(TFInggris);
        TFInggris.setBounds(55, 315, 250, 25);

        TFMtk.setForeground(new java.awt.Color(102, 102, 102));
        TFMtk.setText("Nilai Rata-Rata Semster 1 - 5");
        TFMtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMtkActionPerformed(evt);
            }
        });
        getContentPane().add(TFMtk);
        TFMtk.setBounds(55, 378, 250, 25);

        TFPilihan.setForeground(new java.awt.Color(102, 102, 102));
        TFPilihan.setText("Nilai Rata-Rata Semster 1 - 5");
        getContentPane().add(TFPilihan);
        TFPilihan.setBounds(55, 441, 250, 25);

        bLanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Submit.png"))); // NOI18N
        bLanjut.setBorder(null);
        bLanjut.setBorderPainted(false);
        bLanjut.setContentAreaFilled(false);
        getContentPane().add(bLanjut);
        bLanjut.setBounds(140, 490, 87, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-IPA.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFInggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFInggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFInggrisActionPerformed

    private void TFMtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMtkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFIndonesia;
    private javax.swing.JTextField TFInggris;
    private javax.swing.JTextField TFMtk;
    private javax.swing.JTextField TFPilihan;
    private javax.swing.JButton b3Bar;
    private javax.swing.JButton bLanjut;
    private javax.swing.JButton bLogoutInputScore;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
    
    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    // BUTTON
    public JButton getB3Bar() {
        return b3Bar;
    }

    public JButton getBLogoutInputScore() {
        return bLogoutInputScore;
    }

    public String getTFIndonesia() {
        return TFIndonesia.getText();
    }
    
    public String getTFInggris() {
        return TFInggris.getText();
    }

    public String getTFMtk() {
        return TFMtk.getText();
    }

    public String getTFPilihan() {
        return TFPilihan.getText();
    }

    public JButton getBLanjut() {
        return bLanjut;
    }

    public void setTFIndonesia(String x) {
        TFIndonesia.setText(x);
    }

    public void setTFInggris(String x) {
        TFInggris.setText(x);
    }

    public void setTFMtk(String x) {
        TFMtk.setText(x);
    }

    public void setTFPilihan(String x) {
        TFPilihan.setText(x);
    }
    
    
    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        bLanjut.addActionListener(e);
        b3Bar.addActionListener(e);   
        bLogoutInputScore.addActionListener(e);
    }
    
    // RESET
    
    public void reset(){
        setTFInggris("");
        setTFIndonesia("");
        setTFMtk("");
        setTFPilihan("");
    }
}
