package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 1 Irsyad Muhamad Al Anshori
 * 
 */

public class viewListPersonality extends javax.swing.JFrame {

    /**
     * Creates new form ListPersonality
     */
    public viewListPersonality() {
        initComponents();
        this.setLocation(515, 45);
        setSize(375,675);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bINTP = new javax.swing.JButton();
        bINTJ = new javax.swing.JButton();
        bINFP = new javax.swing.JButton();
        bINFJ = new javax.swing.JButton();
        bESTP = new javax.swing.JButton();
        bESTJ = new javax.swing.JButton();
        bESFP = new javax.swing.JButton();
        bESFJ = new javax.swing.JButton();
        bENFJ = new javax.swing.JButton();
        bENFP = new javax.swing.JButton();
        bENTJ = new javax.swing.JButton();
        bENTP = new javax.swing.JButton();
        bLogoutMUser = new javax.swing.JButton();
        b3BarMUser = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bINTP.setBackground(new java.awt.Color(255, 255, 255));
        bINTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/INTP.png"))); // NOI18N
        bINTP.setBorder(null);
        bINTP.setBorderPainted(false);
        bINTP.setContentAreaFilled(false);
        getContentPane().add(bINTP);
        bINTP.setBounds(270, 450, 69, 137);

        bINTJ.setBackground(new java.awt.Color(255, 255, 255));
        bINTJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/INTJ.png"))); // NOI18N
        bINTJ.setBorder(null);
        bINTJ.setBorderPainted(false);
        bINTJ.setContentAreaFilled(false);
        getContentPane().add(bINTJ);
        bINTJ.setBounds(190, 450, 69, 137);

        bINFP.setBackground(new java.awt.Color(255, 255, 255));
        bINFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/INFP.png"))); // NOI18N
        bINFP.setBorder(null);
        bINFP.setBorderPainted(false);
        bINFP.setContentAreaFilled(false);
        getContentPane().add(bINFP);
        bINFP.setBounds(110, 450, 69, 137);

        bINFJ.setBackground(new java.awt.Color(255, 255, 255));
        bINFJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/INFJ.png"))); // NOI18N
        bINFJ.setBorder(null);
        bINFJ.setBorderPainted(false);
        bINFJ.setContentAreaFilled(false);
        getContentPane().add(bINFJ);
        bINFJ.setBounds(30, 450, 70, 137);

        bESTP.setBackground(new java.awt.Color(255, 255, 255));
        bESTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ESTP.png"))); // NOI18N
        bESTP.setBorder(null);
        bESTP.setBorderPainted(false);
        bESTP.setContentAreaFilled(false);
        getContentPane().add(bESTP);
        bESTP.setBounds(270, 305, 70, 137);

        bESTJ.setBackground(new java.awt.Color(255, 255, 255));
        bESTJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ESTJ.png"))); // NOI18N
        bESTJ.setBorder(null);
        bESTJ.setBorderPainted(false);
        bESTJ.setContentAreaFilled(false);
        getContentPane().add(bESTJ);
        bESTJ.setBounds(190, 305, 69, 137);

        bESFP.setBackground(new java.awt.Color(255, 255, 255));
        bESFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ESFP.png"))); // NOI18N
        bESFP.setBorder(null);
        bESFP.setBorderPainted(false);
        bESFP.setContentAreaFilled(false);
        getContentPane().add(bESFP);
        bESFP.setBounds(110, 305, 70, 137);

        bESFJ.setBackground(new java.awt.Color(255, 255, 255));
        bESFJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ESFJ.png"))); // NOI18N
        bESFJ.setBorder(null);
        bESFJ.setBorderPainted(false);
        bESFJ.setContentAreaFilled(false);
        getContentPane().add(bESFJ);
        bESFJ.setBounds(30, 305, 69, 137);

        bENFJ.setBackground(new java.awt.Color(255, 255, 255));
        bENFJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ENFJ.png"))); // NOI18N
        bENFJ.setBorder(null);
        bENFJ.setBorderPainted(false);
        bENFJ.setContentAreaFilled(false);
        getContentPane().add(bENFJ);
        bENFJ.setBounds(30, 160, 69, 137);

        bENFP.setBackground(new java.awt.Color(255, 255, 255));
        bENFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ENFP.png"))); // NOI18N
        bENFP.setBorder(null);
        bENFP.setBorderPainted(false);
        bENFP.setContentAreaFilled(false);
        getContentPane().add(bENFP);
        bENFP.setBounds(110, 160, 70, 137);

        bENTJ.setBackground(new java.awt.Color(255, 255, 255));
        bENTJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ENTJ.png"))); // NOI18N
        bENTJ.setBorder(null);
        bENTJ.setBorderPainted(false);
        bENTJ.setContentAreaFilled(false);
        getContentPane().add(bENTJ);
        bENTJ.setBounds(190, 160, 70, 137);

        bENTP.setBackground(new java.awt.Color(255, 255, 255));
        bENTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ENTP.png"))); // NOI18N
        bENTP.setBorder(null);
        bENTP.setBorderPainted(false);
        bENTP.setContentAreaFilled(false);
        getContentPane().add(bENTP);
        bENTP.setBounds(270, 160, 70, 137);

        bLogoutMUser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Logout.png"))); // NOI18N
        bLogoutMUser.setBorder(null);
        bLogoutMUser.setBorderPainted(false);
        bLogoutMUser.setContentAreaFilled(false);
        bLogoutMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMUserActionPerformed(evt);
            }
        });
        getContentPane().add(bLogoutMUser);
        bLogoutMUser.setBounds(260, 108, 90, 27);

        b3BarMUser.setBackground(new java.awt.Color(255, 255, 255));
        b3BarMUser.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Back.png"))); // NOI18N
        b3BarMUser.setBorder(null);
        b3BarMUser.setContentAreaFilled(false);
        b3BarMUser.setDefaultCapable(false);
        getContentPane().add(b3BarMUser);
        b3BarMUser.setBounds(21, 45, 15, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BG-List Personality.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutMUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarMUser;
    private javax.swing.JButton bENFJ;
    private javax.swing.JButton bENFP;
    private javax.swing.JButton bENTJ;
    private javax.swing.JButton bENTP;
    private javax.swing.JButton bESFJ;
    private javax.swing.JButton bESFP;
    private javax.swing.JButton bESTJ;
    private javax.swing.JButton bESTP;
    private javax.swing.JButton bINFJ;
    private javax.swing.JButton bINFP;
    private javax.swing.JButton bINTJ;
    private javax.swing.JButton bINTP;
    private javax.swing.JButton bLogoutMUser;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    // MESSAGE
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    // BUTTON
    
    public JButton getB3BarMUser() {
        return b3BarMUser;
    }

    public JButton getBLogoutMUser() {
        return bLogoutMUser;
    }

    public JButton getbENFJ() {
        return bENFJ;
    }

    public JButton getbENFP() {
        return bENFP;
    }

    public JButton getbENTJ() {
        return bENTJ;
    }

    public JButton getbENTP() {
        return bENTP;
    }

    public JButton getbESFJ() {
        return bESFJ;
    }

    public JButton getbESFP() {
        return bESFP;
    }

    public JButton getbESTJ() {
        return bESTJ;
    }

    public JButton getbESTP() {
        return bESTP;
    }

    public JButton getbINFJ() {
        return bINFJ;
    }

    public JButton getbINFP() {
        return bINFP;
    }

    public JButton getbINTJ() {
        return bINTJ;
    }

    public JButton getbINTP() {
        return bINTP;
    }

//    public JButton getbISFJ() {
//        return bISFJ;
//    }
//
//    public JButton getbISFP() {
//        return bISFP;
//    }
//
//    public JButton getbISTJ() {
//        return bISTJ;
//    }
//
//    public JButton getbISTP() {
//        return bISTP;
//    }

    // ACTION LISTENER
    
    public void addActionListener (ActionListener e) {
        b3BarMUser.addActionListener(e);
        bLogoutMUser.addActionListener(e);    
        bENFJ.addActionListener(e);
        bENFP.addActionListener(e);
        bENTJ.addActionListener(e);
        bENTP.addActionListener(e);
        bESFJ.addActionListener(e);
        bESFP.addActionListener(e);
        bESTJ.addActionListener(e);
        bESTP.addActionListener(e);
        bINFJ.addActionListener(e);
        bINFP.addActionListener(e);
        bINTJ.addActionListener(e);
        bINTP.addActionListener(e);
//        bISFJ.addActionListener(e);
//        bISFP.addActionListener(e);
//        bISTJ.addActionListener(e);
//        bISTP.addActionListener(e);
    }
}
